# -*- coding: utf-8 -*-
"""SVM1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OrZ49YXyulWlcwtZxAyzB-wZR7qTK5YQ
"""

import pandas as pd
import numpy as np

data1=pd.read_csv('/content/dataset.zip')

data1

x=data1.iloc[:,:-1]
y=data1.iloc[:,-1]

print(x.shape)
print(y.shape)

df=pd.DataFrame(x)

df

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y)

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

from sklearn.svm import SVC
alg1=SVC()

alg1.fit(x_train,y_train)

y_pred=alg1.predict(x_test)

accuracy=alg1.score(x_test,y_test)

print(accuracy)

accuracy2=alg1.score(x_train,y_train)

print(accuracy2)

import matplotlib.pyplot as plt

plt.scatter(y_test,y_pred,color='red')
plt.plot([y_test.min(),y_test.max()],[y_test.min(),y_test.max()],color='green',linewidth=3)
plt.show()

plt.figure(figsize=(10,10))
plt.scatter(y_test,y_pred,color='black',alpha=0.5)
plt.plot([y_test.min(),y_test.max()],[y_test.min(),y_test.max()],color='blue',linewidth=3)
plt.xlabel('Actual')
plt.ylabel('predicted')
plt.title('actual vs predicted Blood donation progression')
plt.grid(True)
plt.show()

